import json
from pathlib import Path

def ref(kind, name): return {'$ref': f'#/components/{kind}/{name}'}
def schema(name): return ref('schemas', name)
def header(name): return ref('headers', name)
def response(name): return ref('responses', name)
def obj(properties, required=None):
    return {'type':'object','properties':properties,'required':required or list(properties),'additionalProperties':False}
def integer(minimum=0): return {'type':'integer','minimum':minimum,'maximum':9007199254740991}
string={'type':'string'}
id_schema={'type':'string','minLength':1,'maxLength':128,'pattern':'^[A-Za-z0-9_-]+$'}
uri={'type':'string','format':'uri','pattern':'^https://'}
order_example={'id':'ord_001','tenantId':'tenant_01','status':'pending','totalCents':1299,'links':{'self':'https://api.example.com/orders/ord_001'}}
page_example={'items':[order_example],'pagination':{'page':1,'pageSize':50,'totalItems':1,'totalPages':1}}
headers={'RequestId':{'description':'Required on every response. A fresh server-generated opaque request identifier, including on idempotent replays.','required':True,'schema':{'type':'string','minLength':1}},'CacheControl':{'required':True,'description':'Private order data is never cached.','schema':{'type':'string','enum':['no-store']}},'Location':{'required':True,'description':'Absolute canonical URL of the created order.','schema':uri},'ETag':{'required':True,'description':'Strong validator of the returned order representation; changes when status changes.','schema':{'type':'string','pattern':'^"[^"\\r\\n]+"$'},'example':'"order-001-r1"'},'Link':{'description':'Absolute RFC 8288 navigation URLs. Preserve status and pageSize. For nonempty results include first and last, previous if page > 1 (capped to last page), next if page < totalPages. Omit Link when totalItems = 0. No links in the collection body.','schema':string,'example':'<https://api.example.com/orders?page=1&pageSize=50>; rel="first", <https://api.example.com/orders?page=1&pageSize=50>; rel="last"'},'WWWAuthenticate':{'required':True,'description':'Bearer challenge; invalid credentials add error="invalid_token".','schema':string,'example':'Bearer realm="orders"'}}
common_headers={'Request-Id':header('RequestId'),'Cache-Control':header('CacheControl')}
schemas={'OrderStatus':{'type':'string','enum':['pending','shipped']},'CreateOrder':obj({'totalCents':{**integer(),'description':'Nonnegative integer cents in the tenant-configured currency. The tenant uses one fixed currency; conversion and client-selected currencies are unsupported.'}}),'Order':obj({'id':{**id_schema,'readOnly':True,'description':'Server-generated, globally unique, immutable opaque identifier.'},'tenantId':{**id_schema,'readOnly':True,'description':'Immutable owner from the validated principal tenant context; never client-supplied.'},'status':{**schema('OrderStatus'),'readOnly':True,'description':'Created pending. Authoritative fulfillment may move pending to shipped; shipped is terminal. This API exposes no transition operation.'},'totalCents':integer(),'links':obj({'self':uri})}),'PagePagination':obj({'page':integer(1),'pageSize':{'type':'integer','minimum':1,'maximum':100},'totalItems':integer(),'totalPages':integer()}),'OrderCollection':obj({'items':{'type':'array','maxItems':100,'items':schema('Order')},'pagination':schema('PagePagination')}),'Problem':{'type':'object','required':['type','title','status','detail','instance'],'properties':{'type':{'type':'string','format':'uri-reference'},'title':string,'status':{'type':'integer','minimum':400,'maximum':599},'detail':string,'instance':{'type':'string','format':'uri-reference'},'errors':{'type':'array','minItems':1,'items':obj({'pointer':{'type':'string','pattern':'^#/(body|query|path|headers)(/.*)?$','description':'JSON Pointer fragment into logical request body, query, path, or headers.'},'detail':string})}},'additionalProperties':True}}
schemas['Order']['example']=order_example
schemas['CreateOrder']['example']={'totalCents':1299}
schemas['OrderCollection']['example']=page_example
responses={}
for name,status,title,description in [('BadRequest',400,'Bad Request','Malformed JSON, invalid query/path syntax, unknown query parameters, or missing/malformed Idempotency-Key.'),('Unauthorized',401,'Unauthorized','Missing or invalid bearer credential.'),('Forbidden',403,'Forbidden','Authenticated principal lacks the requested collection or operation permission, or lacks one trusted tenant context.'),('NotFound',404,'Not Found','Order is absent or belongs to another tenant; return identical concealed response.'),('NotAcceptable',406,'Not Acceptable','Accept excludes supported response representations.'),('Conflict',409,'Conflict','Same idempotency key is still processing. Retry with the same key and body after completion.'),('UnsupportedMediaType',415,'Unsupported Media Type','Creation requires application/json.'),('ValidationError',422,'Unprocessable Content','Valid JSON violates the create schema, or the same idempotency key is reused with a different normalized body.'),('InternalError',500,'Internal Server Error','Unexpected server failure; no implementation details or secrets are exposed.')]:
    ex={'type':'about:blank','title':title,'status':status,'detail':description,'instance':'urn:request:req_001'}
    if status==422:
        ex.update(type='https://api.example.com/problems/validation-error',title='Request validation failed',errors=[{'pointer':'#/body/totalCents','detail':'must be a nonnegative integer'}])
    responses[name]={'description':description,'headers':dict(common_headers),'content':{'application/problem+json':{'schema':schema('Problem'),'example':ex}}}
responses['Unauthorized']['headers']['WWW-Authenticate']=header('WWWAuthenticate')
parameters={}
for name,location,required,shape,desc in [('Page','query',False,{**integer(1),'default':1},'One-based page. Beyond the last page returns 200 and empty items, retaining requested page.'),('PageSize','query',False,{'type':'integer','minimum':1,'maximum':100,'default':50},'Maximum orders on the requested page.'),('Status','query',False,schema('OrderStatus'),'Exact equality filter on order status. Omission includes both states.'),('OrderId','path',True,id_schema,'Globally unique opaque order ID.'),('IdempotencyKey','header',True,{'type':'string','pattern':'^"[A-Za-z0-9_-]{1,128}"$'},'Project deduplication header, an RFC 8941 quoted string. Reuse the same value for retries of one creation.')]:
    wire={'Page':'page','PageSize':'pageSize','Status':'status','OrderId':'orderId','IdempotencyKey':'Idempotency-Key'}[name]
    parameters[name]={'name':wire,'in':location,'required':required,'style':'form' if location=='query' else 'simple','explode':location=='query','schema':shape,'description':desc}

def success(status, name, example, extras=None):
    return {str(status):{'description':'Order created.' if status==201 else 'Successful read.','headers':{**common_headers,**(extras or {})},'content':{'application/json':{'schema':schema(name),'example':example}}}}
def operation(oid,summary,description,params,ok,failures):
    return {'operationId':oid,'tags':['Orders'],'summary':summary,'description':description,'security':[{'bearerAuth':[]}],'parameters':[ref('parameters',p) for p in params],'responses':{**ok,**{str(responses[n]['content']['application/problem+json']['example']['status']):response(n) for n in failures}}}
common_failures=['BadRequest','Unauthorized','Forbidden','NotAcceptable','InternalError']
create=operation('createOrder','Create an order','Authorize creation in the trusted tenant. Assign immutable globally unique id and tenantId and initial pending status. Require a deduplication key because duplicate orders are costly. Key scope: validated issuer + subject + tenant + POST + canonical /orders. Retain successful outcomes for 24 hours from completion. Fingerprint is the validated normalized JSON body (key ordering and insignificant whitespace ignored). Atomically persist the order and successful deduplication result. Same key and body during retention replays original 201 body, Location, and ETag with a fresh Request-Id; original body can have an older status than current GET. Different body returns 422 with pointer #/headers/Idempotency-Key; in-flight duplicate returns 409. Authorization is checked on every replay. Failed validation does not reserve a key. Unknown outcomes may be retried with the same key within 24 hours; after expiry a retry can create a duplicate. This is bounded deduplication, not exactly-once execution.',['IdempotencyKey'],success(201,'Order',order_example,{'Location':header('Location'),'ETag':header('ETag')}),common_failures+['UnsupportedMediaType','ValidationError','Conflict'])
create['requestBody']={'required':True,'content':{'application/json':{'schema':schema('CreateOrder'),'example':{'totalCents':1299}}}}
listing=operation('listOrders','List orders','Only orders authorized for the principal in the trusted tenant are eligible. Apply authorization and status filter before counting and pagination. Order by id ascending using bytewise ASCII comparison; id is globally unique and is the deterministic tie-breaker. Calculate items and exact totalItems from the same read snapshot per request. totalPages = ceil(totalItems / pageSize), or 0 when empty. Each request sees fresh state; no cross-request snapshot guarantee, so concurrent inserts or status changes can shift numbered pages. Unknown, duplicate, or invalid query parameters return 400. GET can be retried safely.',['Status','Page','PageSize'],success(200,'OrderCollection',page_example,{'Link':header('Link')}),common_failures)
getting=operation('getOrder','Get an order','Authorize get permission and verify the order belongs to the principal trusted tenant. Cross-tenant and absent orders both return 404. GET can be retried safely.',['OrderId'],success(200,'Order',order_example,{'ETag':header('ETag')}),common_failures+['NotFound'])
doc={'openapi':'3.1.0','info':{'title':'Orders API','version':'0.1.0','description':'Reviewable new contract for create, get and status-filtered list. The example HTTPS origin is a deployment placeholder. No API version selector is currently needed. Amount is integer cents in one fixed tenant-configured currency. Resource relationships beyond self are not exposed because no tenant API is defined.'},'servers':[{'url':'https://api.example.com','description':'Placeholder; replace with the real HTTPS origin before deployment.'}],'tags':[{'name':'Orders','description':'Order identity, ownership, amounts and lifecycle.'}],'paths':{'/orders':{'post':create,'get':listing},'/orders/{orderId}':{'get':getting}},'components':{'schemas':schemas,'parameters':parameters,'headers':headers,'responses':responses,'securitySchemes':{'bearerAuth':{'type':'http','scheme':'bearer','description':'Use an existing trusted bearer issuer. Validate issuer, audience, signature/proof, expiry and revocation before deriving subject and exactly one tenant context. Credentials do not by themselves authorize an operation. Enforce operation permission and authoritative tenant ownership separately. Issuer deployment configuration is outside this design.'}}}}
Path('openapi.json').write_text(json.dumps(doc,ensure_ascii=False,indent=2)+'\n')
